server:
  port: 8762

spring:
  application:
    name: eureka-server
  security:
    user:
      name: eureka
      password: eurekasecret

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
