spring:
  application:
    name: user-service
    description: User Service
    version: 1.0.0
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: postgres
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

jwt:
  config:
    secret: 469f3debf3d3e525ccf4d16b3a7634bc7b2f5cc1
    expire: 86400000

management:
  endpoints:
    web:
      exposure:
        include: info,health
  endpoint:
    health:
      show-details: always

info:
  app:
    name: ${spring.application.name}
    description: ${spring.application.description}
    version: ${spring.application.version}

eureka:
  client:
    service-url:
      defaultZone: http://eureka:eurekasecret@localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true